<a href="https://colab.research.google.com/github/AbR04/6thSem-ML-Lab/blob/main/1BM22CS005_LAB_2_DataProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv("/content/housing.csv")

In [ ]:
print("Sample data:")
print(df.head())
print("\n")

Sample data:
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0
1    -122.22     37.86                21.0       7099.0          1106.0
2    -122.24     37.85                52.0       1467.0           190.0
3    -122.25     37.85                52.0       1274.0           235.0
4    -122.25     37.85                52.0       1627.0           280.0

   population  households  median_income  median_house_value ocean_proximity
0       322.0       126.0         8.3252            452600.0        NEAR BAY
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY
2       496.0       177.0         7.2574            352100.0        NEAR BAY
3       558.0       219.0         5.6431            341300.0        NEAR BAY
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [ ]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
unique_counts = df['ocean_proximity'].unique()
print(unique_counts)

['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']

In [ ]:
missing = df.isnull().sum()

columns_with_missing_values = missing[missing > 0]

print(columns_with_missing_values)

total_bedrooms    207
dtype: int64

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, StandardScaler

file_path = "DatasetofDiabetes.csv"
df = pd.read_csv(file_path)


df_numeric = df.select_dtypes(include=['number']).copy()


imputer = SimpleImputer(strategy="mean")


df_numeric.iloc[:, :] = imputer.fit_transform(df_numeric)


df[df_numeric.columns] = df_numeric

Q1 = df_numeric.quantile(0.25)
Q3 = df_numeric.quantile(0.75)
IQR = Q3 - Q1

df = df[~((df_numeric < (Q1 - 1.5 * IQR)) | (df_numeric > (Q3 + 1.5 * IQR))).any(axis=1)]


min_max_scaler = MinMaxScaler()
df_minmax = pd.DataFrame(min_max_scaler.fit_transform(df_numeric), columns=df_numeric.columns) # Only transform the numeric columns

standard_scaler = StandardScaler()
df_standard = pd.DataFrame(standard_scaler.fit_transform(df_numeric), columns=df_numeric.columns)  # Only transform the numeric columns

print("\nProcessed Diabetes Dataset (Min-Max Scaled):")
print(df_minmax.head())

print("\nProcessed Diabetes Dataset (Standard Scaled):")
print(df_standard.head())

Processed Diabetes Dataset (Min-Max Scaled):
         ID  No_Pation       AGE      Urea        Cr     HbA1c      Chol  \
0  0.627034   0.000237  0.508475  0.109375  0.050378  0.264901  0.407767
1  0.918648   0.000452  0.101695  0.104167  0.070529  0.264901  0.359223
2  0.524406   0.000634  0.508475  0.109375  0.050378  0.264901  0.407767
3  0.849812   0.001160  0.508475  0.109375  0.050378  0.264901  0.407767
4  0.629537   0.000452  0.220339  0.171875  0.050378  0.264901  0.475728

         TG       HDL       LDL      VLDL       BMI
0  0.044444  0.226804  0.114583  0.011461  0.173913
1  0.081481  0.092784  0.187500  0.014327  0.139130
2  0.044444  0.226804  0.114583  0.011461  0.173913
3  0.044444  0.226804  0.114583  0.011461  0.173913
4  0.051852  0.061856  0.177083  0.008596  0.069565

Processed Diabetes Dataset (Standard Scaled):
         ID  No_Pation       AGE      Urea        Cr     HbA1c      Chol  \
0  0.672140  -0.074747 -0.401144 -0.144781 -0.382672 -1.334983 -0.509436
1  1.641852  -0.069940 -3.130017 -0.212954 -0.115804 -1.334983 -0.893730
2  0.330868  -0.065869 -0.401144 -0.144781 -0.382672 -1.334983 -0.509436
3  1.412950  -0.054126 -0.401144 -0.144781 -0.382672 -1.334983 -0.509436
4  0.680463  -0.069939 -2.334096  0.673299 -0.382672 -1.334983  0.028576

         TG       HDL       LDL      VLDL       BMI
0 -1.035084  1.810756 -1.085457 -0.369958 -1.124622
1 -0.678063 -0.158692 -0.457398 -0.342649 -1.326239
2 -1.035084  1.810756 -1.085457 -0.369958 -1.124622
3 -1.035084  1.810756 -1.085457 -0.369958 -1.124622
4 -0.963680 -0.613180 -0.547121 -0.397267 -1.729472

In [ ]:
import pandas as pd

file_path = "DatasetofDiabetes.csv"
df = pd.read_csv(file_path)
# Assuming 'df' is your DataFrame
missing_values = df.isnull()

# Create a new DataFrame to show where the missing values are
missing_value_columns = missing_values.sum()

# Show only columns that have missing values
missing_value_columns = missing_value_columns[missing_value_columns > 0]

print("Columns with missing values and their count:")
print(missing_value_columns)

Columns with missing values and their count:
Series([], dtype: int64)

In [ ]:
# Step 1: Import required libraries
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder

# Step 2: Load the Adult Income dataset (Ensure it's uploaded to Colab)
file_path = "adult.csv"  # Update the path if needed
df = pd.read_csv(file_path)

# Step 3: Handling Missing Values (Replacing '?' with NaN and imputing mode for categorical, mean for numerical)
df.replace("?", np.nan, inplace=True)

# Handling numerical missing values with mean
num_imputer = SimpleImputer(strategy="mean")
df[df.select_dtypes(include=['number']).columns] = num_imputer.fit_transform(df.select_dtypes(include=['number']))

# Handling categorical missing values with mode
cat_imputer = SimpleImputer(strategy="most_frequent")
df[df.select_dtypes(include=['object']).columns] = cat_imputer.fit_transform(df.select_dtypes(include=['object']))

# Step 4: Handling Categorical Data (Encoding)
label_encoders = {}
for col in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# Step 5: Handling Outliers (Removing values beyond 1.5*IQR)
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
df = df[~((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)]

# Step 6: Data Transformation
# Min-Max Normalization
min_max_scaler = MinMaxScaler()
df_minmax = pd.DataFrame(min_max_scaler.fit_transform(df), columns=df.columns)

# Standardization (Z-score normalization)
standard_scaler = StandardScaler()
df_standard = pd.DataFrame(standard_scaler.fit_transform(df), columns=df.columns)

# Step 7: Display Processed Data
print("\nProcessed Adult Income Dataset (Min-Max Scaled):")
print(df_minmax.head())

print("\nProcessed Adult Income Dataset (Standard Scaled):")
print(df_standard.head())

Processed Adult Income Dataset (Min-Max Scaled):
        age  workclass    fnlwgt  education  educational-num  marital-status  \
0  0.344262        0.0  0.188277   0.555556         0.363636        0.333333
1  0.114754        0.0  0.881156   1.000000         0.454545        0.666667
2  0.147541        0.0  0.169156   0.555556         0.363636        0.666667
3  0.672131        0.0  0.708251   0.555556         0.363636        0.333333
4  0.131148        0.0  0.475807   0.333333         0.727273        0.333333

   occupation  relationship  race  gender  capital-gain  capital-loss  \
0    0.307692           0.0   0.0     1.0           0.0           0.0
1    0.538462           0.8   0.0     0.0           0.0           0.0
2    0.000000           0.2   0.0     0.0           0.0           0.0
3    0.692308           0.0   0.0     1.0           0.0           0.0
4    0.692308           0.0   0.0     1.0           0.0           0.0

   hours-per-week  native-country  income
0        0.894737             0.0     0.0
1        0.368421             0.0     0.0
2        0.315789             0.0     0.0
3        0.105263             0.0     0.0
4        0.368421             0.0     0.0

Processed Adult Income Dataset (Standard Scaled):
        age  workclass    fnlwgt  education  educational-num  marital-status  \
0  0.220179        0.0 -1.022983  -0.151256        -0.654083       -0.398228
1 -0.955630        0.0  2.234629   1.457372        -0.073261        0.828047
2 -0.787657        0.0 -1.112882  -0.151256        -0.654083        0.828047
3  1.899906        0.0  1.421707  -0.151256        -0.654083       -0.398228
4 -0.871644        0.0  0.328856  -0.955571         1.669207       -0.398228

   occupation  relationship  race    gender  capital-gain  capital-loss  \
0   -0.420679     -1.044582   0.0  0.770972           0.0           0.0
1    0.305840      1.629927   0.0 -1.297064           0.0           0.0
2   -1.389371     -0.375955   0.0 -1.297064           0.0           0.0
3    0.790186     -1.044582   0.0  0.770972           0.0           0.0
4    0.790186     -1.044582   0.0  0.770972           0.0           0.0

   hours-per-week  native-country  income
0        2.312838             0.0     0.0
1       -0.329781             0.0     0.0
2       -0.594043             0.0     0.0
3       -1.651090             0.0     0.0
4       -0.329781             0.0     0.0

In [ ]:
# Handling numerical missing values with mean
num_imputer = SimpleImputer(strategy="mean")
df[df.select_dtypes(include=['number']).columns] = num_imputer.fit_transform(df.select_dtypes(include=['number']))

# Handling categorical missing values with mode
cat_imputer = SimpleImputer(strategy="most_frequent")
df[df.select_dtypes(include=['object']).columns] = cat_imputer.fit_transform(df.select_dtypes(include=['object']))

ValueError: at least one array or dtype is required